from collections.abc import Callable
from decimal import Decimal
from typing import Any, Protocol, TypeAlias

from .models import Operator


class SupportsMathOperator(Protocol):
    def __add__(self, other: Any, /) -> Any: ...
    def __radd__(self, other: Any, /) -> Any: ...
    def __sub__(self, other: Any, /) -> Any: ...
    def __rsub__(self, other: Any, /) -> Any: ...
    def __mul__(self, other: Any, /) -> Any: ...
    def __rmul__(self, other: Any, /) -> Any: ...
    def __truediv__(self, other: Any, /) -> Any: ...
    def __rtruediv__(self, other: Any, /) -> Any: ...
    def __mod__(self, other: Any, /) -> Any: ...
    def __rmod__(self, other: Any, /) -> Any: ...
    def __floordiv__(self, other: Any, /) -> Any: ...
    def __rfloordiv__(self, other: Any, /) -> Any: ...
    def __pow__(self, other: Any, /) -> Any: ...
    def __rpow__(self, other: Any, /) -> Any: ...
    def __pos__(self) -> Any: ...
    def __neg__(self) -> Any: ...
    def __abs__(self) -> Any: ...


OperatorFn: TypeAlias = Callable[[SupportsMathOperator, SupportsMathOperator], SupportsMathOperator]


def _safe_operate(fn: OperatorFn) -> OperatorFn:
    def inner(a: SupportsMathOperator, b: SupportsMathOperator) -> SupportsMathOperator:
        if isinstance(a, Decimal) and isinstance(b, float):
            b = Decimal.from_float(b)

        if isinstance(b, Decimal) and isinstance(a, float):
            a = Decimal.from_float(a)

        return fn(a, b)

    return inner


OPERATORS: dict[Operator, tuple[OperatorFn, str]] = {
    "add": (_safe_operate(lambda a, b: a + b), "+"),
    "subtract": (_safe_operate(lambda a, b: a - b), "-"),
    "multiply": (_safe_operate(lambda a, b: a * b), "*"),
    "divide": (_safe_operate(lambda a, b: a / b), "/"),
    "modulo": (_safe_operate(lambda a, b: a % b), "%"),
    "floor_divide": (_safe_operate(lambda a, b: a // b), "//"),
    "power": (_safe_operate(lambda a, b: a**b), "**"),
}
